### PR TITLE
Privacy & Data Retention Updates

### PR DESCRIPTION
**Pull request by kfriedman**
This is intended to address Privacy & Data Retention responsibilities for the Engineering team. For now, it adds two things:

- A stub Privacy & Data Retention Standards document that we can iterate on.
- An addition to the Production Readiness Standards to add that Privacy & Data Retention Standards should be reviewed during the Production Readiness process.

Suggestions?

### CODE REVIEW

**Comment by kfriedman** [comment]
Hi y'all,

I'd like to merge this PR but make sure it has some visibility since it's a fairly big deal. Basically, this PR establishes a couple of things:

1. Adding a "Privacy & Data Retention" standard (really a stub for now)
2. Adding "Privacy & Data Retention" to our Production Readiness process

This isn't intended to be comprehensive but really just a start towards a more formal policy.

**Comment by nodanaonlyzuul** [comment]
**Is this regarding PII of patrons only?**

It's hard to imagine us spinning up an app for staff (which would probably track their name & email) without approval of "...appropriate Product and Engineering management" but still...

Just curious - are there retention standards out there that we use that actionable not aspirational? 
GDPR I guess? Now I'm just thinking outloud....

**Comment by EdwinGuzman** [comment]
Is there a reason why it's more than 7 days or that an arbitrary number?

**Comment by kfriedman** [comment]
@nodanaonlyzuul good question, I think the intention of this standard/PR is to address patron privacy. But, you are right, perhaps staff-related privacy issues could also be addressed at a future point.

@EdwinGuzman it is _somewhat_ arbitrary. I think I had in the mind the idea of a queue, stream, cache, etc. that might store data for a small, finite period of time and should be exempt from formal policy.

**Comment by gkallenberg** [comment]
I'm not convinced that this policy decision is ours to make without
consultation of library industry standard practice, legal and others in our
management that should be consulted in making these decisions or refining
our interpretation. Not informing other departments of our practices, in my
opinion, moves us into an operational state apart from the library allowing
us to decide policy on our own without consent or other department heads'
knowledge of these decisions.

Are we communicating what we're deciding to those who's data we're storing
in queues, caches, logs, backups, etc.?

What gives us the power to decide what's exempt from policy and what's not?
What criteria are we using to decide what can be exempted and what cannot?
Will we incur penalties from outside agencies' scrutiny of our practices?

I think there's a larger discussion to be had surrounding security of
patron data, staff data, account data, monetary transaction data, etc. in
whatever form. Do we even know how that data is being governed under AWS?
Is that documented somewhere and can we trust it? I believe there are many
questions to be answered besides what I can think of off the top of my head.

--

*Gregory Kallenberg* | The New York Public Library
*Senior Applications Developer*

Digital Development
40 West 20th Street, 5th Floor, New York, NY 10011
T: 212.621.0283 | gregorykallenberg@nypl.org
<http://www.nypl.org>
*Inspiring Lifelong Learning | Advancing Knowledge | Strengthening Our
Communities*

**Comment by holingpoon** [comment]
My two cents: We are also relying on third party services such as AWS, Optimizely, Loggly, just to name a few, and we need to make sure their privacy policy is in line with ours. We also need to look over which products are IT using, and study those privacy policies, too.

**Comment by EdwinGuzman** [comment]
I agree with all of the above, but as stated in this PR, this is meant to be a stub which I think is fine for now. I do like @holingpoon 's idea of looking at our third party services so we can be aligned with them.

**Comment by kfriedman** [comment]
Thanks to everyone for the feedback. I added a line about third-party products per @holingpoon's suggestion. I think @gkallenberg's questions are great and can be answered as this document is iterated on and policies are fleshed out.

Unless, there are objections - and please comment if you have one - I'm going to merge this PR so we at least have something as part of Production Readiness process.

**Pull request merged**
